name-template: 'v$NEXT_VERSION'
tag-template:  'v$NEXT_VERSION'
prerelease: false

categories:
  - title: 🚀 Features
    labels: [ 'feature', 'enhancement', 'minor' ]
  - title: 🐛 Fixes
    labels: [ 'bug', 'hotfix', 'patch' ]
  - title: 🧰 Maintenance
    labels: [ 'chore', 'refactor', 'docs', 'tests' ]

change-template: '- $TITLE (#$NUMBER)'
version-resolver:
  major:
    labels: [ 'major' ]
  minor:
    labels: [ 'minor', 'feature' ]
  patch:
    labels: [ 'patch', 'hotfix', 'bug' ]
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_VERSION