version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    ports:
      - "1883:1883"
    command: mosquitto -c /mosquitto-no-auth.conf

  postgres:
    image: postgres:15
    container_name: atlas32-postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: atlas32
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
  atlas-server:
    image: marceljungle/atlas-32-server:0.2.4
    ports: ["4046:4046"]
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/atlas32
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      MQTT_BROKER_URL: tcp://mosquitto:1883
