server:
  port: 4046
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  application:
    name: atlas-32
mqtt:
  qos: 1
  topic:
    response:
      subscribe: device/+/response
    command:
      publish: device/+/command
  broker:
    url: ${MQTT_BROKER_URL:tcp://localhost:1883}
  client:
    id: atlas-32

logging:
  level:
    root: INFO
