name: Release Drafter
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, labeled, unlabeled, closed]

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
